/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.IOFile;
import controller.trongghichuException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Bangchi;
import controller.NgayException;
import controller.TrongException;
import controller.numberException;
import controller.trongngayException;
import controller.trongsotienException;
import controller.trongkhoanchiException;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author trung
 */
public class Formbangchi extends javax.swing.JPanel {

    /**
     * Creates new form Formbangchi
     */
    private DefaultTableModel tm;
    private boolean them,sua;
    private List<Bangchi> lbangchi;
    private String fbangchi;
    public Formbangchi() {
        initComponents();
        fbangchi = "src/controller/Bangchi.DAT";
        String[] cols = {"Ngay", "So tien", "Ghi chu", "Khoan chi"};
        tm = new DefaultTableModel(cols, 0);
        tbbangchi.setModel(tm);
        them = false;
        sua = false;
        loadData();
    }
    private void loadData() {
        File f = new File(fbangchi);
        if (f.exists()) {
            lbangchi = IOFile.doc(fbangchi);
            tm.setRowCount(0);
            for (Bangchi i: lbangchi) {
                tm.addRow(i.toObject());
            }
        } 
        else {
            lbangchi = new ArrayList<>();
        }
    }
    private void trangthai(boolean b){
        bthem.setEnabled(b);
        bsua.setEnabled(b);
        bxoa.setEnabled(b);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfngay = new javax.swing.JTextField();
        tfsotien = new javax.swing.JTextField();
        tfghichu = new javax.swing.JTextField();
        tfkhoanchi = new javax.swing.JTextField();
        bcapnhat = new javax.swing.JButton();
        bthem = new javax.swing.JButton();
        bxoa = new javax.swing.JButton();
        bsua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbbangchi = new javax.swing.JTable();
        bboqua = new javax.swing.JButton();

        jLabel1.setText("Ngay");

        jLabel2.setText("So tien");

        jLabel3.setText("Ghi chu");

        jLabel4.setText("khoan thu");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jTextField6))
                .addContainerGap())
        );

        jLabel5.setText("Ngày");

        jLabel6.setText("Số tiền");

        jLabel7.setText("Ghi chú");

        jLabel8.setText("Khoản chi");

        tfngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfngayActionPerformed(evt);
            }
        });

        tfsotien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsotienActionPerformed(evt);
            }
        });

        tfkhoanchi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfkhoanchiActionPerformed(evt);
            }
        });

        bcapnhat.setText("Cập nhật");
        bcapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcapnhatActionPerformed(evt);
            }
        });

        bthem.setText("Thêm");
        bthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthemActionPerformed(evt);
            }
        });

        bxoa.setText("Xóa");
        bxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxoaActionPerformed(evt);
            }
        });

        bsua.setText("Sửa");
        bsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsuaActionPerformed(evt);
            }
        });

        tbbangchi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ngày", "Số tiền", "Ghi chú", "Khoản chi"
            }
        ));
        tbbangchi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbbangchiAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tbbangchi);

        bboqua.setText("Bỏ qua");
        bboqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bboquaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel6)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel7)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfngay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bthem))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfsotien, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bsua)
                                        .addGap(33, 33, 33)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(bcapnhat)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfkhoanchi, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bxoa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bboqua)))))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfsotien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfghichu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfkhoanchi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bthem)
                    .addComponent(bsua)
                    .addComponent(bcapnhat)
                    .addComponent(bxoa)
                    .addComponent(bboqua))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void tfkhoanchiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfkhoanchiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfkhoanchiActionPerformed

    private void tfngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfngayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfngayActionPerformed

    private void tfsotienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsotienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsotienActionPerformed

    private void bthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthemActionPerformed
        trangthai(false);
        them = true;
        if(lbangchi == null || lbangchi.size() < 1)
            lbangchi = new ArrayList<>();
        tfngay.requestFocus();
    }//GEN-LAST:event_bthemActionPerformed

    private void tbbangchiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbbangchiAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbbangchiAncestorAdded

    private void bcapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcapnhatActionPerformed
        // TODO add your handling code here:
        if(them){
            String ngay, sotien, ghichu, khoanchi;
            try{
                ngay = tfngay.getText();
                sotien = tfsotien.getText();
                ghichu = tfghichu.getText();
                khoanchi = tfkhoanchi.getText();
                if(ngay.isEmpty()) throw new trongngayException();
                if (!ngay.matches("^\\d{2}[/]\\d{2}[/]\\d{4}$")) throw new NgayException();
                if(sotien.isEmpty()) throw new trongsotienException();
                if(!sotien.matches("\\d+")) throw new numberException();
                if(ghichu.isEmpty()) throw new trongghichuException();
                if(khoanchi.isEmpty()) throw new trongkhoanchiException();
                
                int tien = Integer.parseInt(sotien);
                Bangchi bc = new Bangchi(ngay , tien, ghichu, khoanchi);
                tm.addRow(bc.toObject());
                lbangchi.add(bc);
                trangthai(true);
                them = false;
            }
            catch(trongngayException e){
                JOptionPane.showMessageDialog(this,"Khong de trong ngay!");
            }
            catch (NgayException e) {
                JOptionPane.showMessageDialog(this,"Nhap dung dinh dang dd/mm/yy");
            }
            catch (trongsotienException e) {
                JOptionPane.showMessageDialog(this,"Khong de trong so tien!");
            } 
            catch (numberException e) {
                JOptionPane.showMessageDialog(this,"Nhap so nguyen duong!");
            }
            catch(trongghichuException e){
                JOptionPane.showMessageDialog(this,"Khong de trong ghi chu!");
            }
            catch (trongkhoanchiException e) {
                JOptionPane.showMessageDialog(this,"Khong de trong khoan chi!");
            }
        }
        if(sua){
            int row = tbbangchi.getSelectedRow();
            String ngay, sotien, ghichu, khoanchi;
            try{
                ngay = tfngay.getText();
                sotien = tfsotien.getText();
                ghichu = tfghichu.getText();
                khoanchi = tfkhoanchi.getText();
                if(ngay.isEmpty()) throw new trongngayException();
                if(sotien.isEmpty()) throw new trongsotienException();
                if(ghichu.isEmpty()) throw new trongghichuException();
                if(khoanchi.isEmpty()) throw new trongkhoanchiException();
                int tien = Integer.parseInt(sotien);
                Bangchi bc = new Bangchi(ngay , tien, ghichu, khoanchi);
                tm.setValueAt(ngay, row, 0);
                tm.setValueAt(sotien, row, 1);
                tm.setValueAt(ghichu, row, 2);
                tm.setValueAt(khoanchi, row, 3);
                lbangchi.set(row, bc);
                trangthai(true);
                sua = false;
            }
            catch(trongngayException e){
                JOptionPane.showMessageDialog(this,"Khong de trong ngay!");
            }
            catch (trongsotienException e) {
                JOptionPane.showMessageDialog(this,"Khong de trong so tien!");
            } 
            catch(trongghichuException e){
                JOptionPane.showMessageDialog(this,"Khong de trong ghi chu!");
            }
            catch (trongkhoanchiException e) {
                JOptionPane.showMessageDialog(this,"Khong de trong khoan chi!");
            }
        }
        IOFile.viet(fbangchi, lbangchi);
        for(Bangchi i: lbangchi){
            System.out.println(i.getSotien()); 
        }
    }//GEN-LAST:event_bcapnhatActionPerformed

    private void bboquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bboquaActionPerformed
        if (them) {
            them = false;
        }
        if (sua) 
            sua = false;
        
        trangthai(true);
    }//GEN-LAST:event_bboquaActionPerformed

    private void bsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsuaActionPerformed
        int row = tbbangchi.getSelectedRow();
        
        if (row < 0 || row > tm.getRowCount()-1) {
            JOptionPane.showMessageDialog(this, "Chon ngay can sua");
        }
        else {
            sua = true;
            trangthai(false);
            tfngay.requestFocus();
        }
    }//GEN-LAST:event_bsuaActionPerformed

    private void bxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxoaActionPerformed
        int row = tbbangchi.getSelectedRow();
        if (row < 0 || row > tm.getRowCount()-1) {
            JOptionPane.showMessageDialog(this, "Chon de xoa");
        } 
        else {
            tm.removeRow(row);
            lbangchi.remove(row);
        }
    }//GEN-LAST:event_bxoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bboqua;
    private javax.swing.JButton bcapnhat;
    private javax.swing.JButton bsua;
    private javax.swing.JButton bthem;
    private javax.swing.JButton bxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTable tbbangchi;
    private javax.swing.JTextField tfghichu;
    private javax.swing.JTextField tfkhoanchi;
    private javax.swing.JTextField tfngay;
    private javax.swing.JTextField tfsotien;
    // End of variables declaration//GEN-END:variables

    private Exception NgayException() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
