/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author trung
 */
import controller.IOFile;
import controller.NgayException;
import controller.numberException;
import controller.trongghichuException;
import controller.trongkhoanchiException;
import controller.trongngayException;
import controller.trongsotienException;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpringLayout;
import javax.swing.table.DefaultTableModel;
import model.Bangthu;
public class Formbangthu extends javax.swing.JPanel {

    /**
     * Creates new form Formbangchi
     */
    private DefaultTableModel tm;
    private boolean them,sua;
    private List<Bangthu> lbangthu;
    private String fbangthu;
    public Formbangthu() {
        initComponents();
        fbangthu = "src/controller/Bangthu.DAT";
        String[] cols = {"Ngay", "So tien", "Ghi chu", "Khoan chi"};
        tm = new DefaultTableModel(cols, 0);
        tbbangthu.setModel(tm);
        them = false;
        sua = false;
        loadData();
    }
    private void loadData() {
        File f = new File(fbangthu);
        if (f.exists()) {
            lbangthu = IOFile.doc(fbangthu);
            tm.setRowCount(0);
            for (Bangthu i: lbangthu) {
                tm.addRow(i.toObject());
            }
        } 
        else {
            lbangthu = new ArrayList<>();
        }
    }
    private void trangthai(boolean b){
        bthem.setEnabled(b);
        bsua.setEnabled(b);
        bxoa.setEnabled(b);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfngay = new javax.swing.JTextField();
        tfsotien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfghichu = new javax.swing.JTextField();
        tfkhoanthu = new javax.swing.JTextField();
        bthem = new javax.swing.JButton();
        bcapnhat = new javax.swing.JButton();
        bsua = new javax.swing.JButton();
        bxoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbbangthu = new javax.swing.JTable();
        bboqua = new javax.swing.JButton();

        tfngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfngayActionPerformed(evt);
            }
        });

        tfsotien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsotienActionPerformed(evt);
            }
        });

        jLabel5.setText("Ngày");

        jLabel6.setText("Số tiền");

        jLabel7.setText("Ghi chú");

        jLabel8.setText("Khoản thu");

        tfghichu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfghichuActionPerformed(evt);
            }
        });

        bthem.setText("Thêm");
        bthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthemActionPerformed(evt);
            }
        });

        bcapnhat.setText("Cập nhật");
        bcapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcapnhatActionPerformed(evt);
            }
        });

        bsua.setText("Sửa");
        bsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsuaActionPerformed(evt);
            }
        });

        bxoa.setText("Xóa");
        bxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxoaActionPerformed(evt);
            }
        });

        tbbangthu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ngày", "Số tiền", "Ghi chú", "Khoản thu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbbangthu);
        if (tbbangthu.getColumnModel().getColumnCount() > 0) {
            tbbangthu.getColumnModel().getColumn(0).setResizable(false);
            tbbangthu.getColumnModel().getColumn(3).setResizable(false);
        }

        bboqua.setText("Bỏ qua");
        bboqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bboquaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfngay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bthem))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfsotien, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bsua)
                                        .addGap(33, 33, 33)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(tfghichu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(bcapnhat)
                                        .addGap(63, 63, 63)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfkhoanthu, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bxoa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bboqua))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel6)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel7)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel8)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfsotien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfghichu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfkhoanthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bthem)
                    .addComponent(bsua)
                    .addComponent(bcapnhat)
                    .addComponent(bxoa)
                    .addComponent(bboqua))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfngayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfngayActionPerformed

    private void tfsotienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsotienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsotienActionPerformed

    private void tfghichuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfghichuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfghichuActionPerformed

    private void bsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsuaActionPerformed
        int row = tbbangthu.getSelectedRow();
        
        if (row < 0 || row > tm.getRowCount()-1) {
            JOptionPane.showMessageDialog(this, "Chon ngay can sua");
        }
        else {
            sua = true;
            trangthai(false);
            tfngay.requestFocus();
        }
    }//GEN-LAST:event_bsuaActionPerformed

    private void bcapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcapnhatActionPerformed
        if(them){
            String ngay, sotien, ghichu, khoanthu;
            try{
                ngay = tfngay.getText();
                sotien = tfsotien.getText();
                ghichu = tfghichu.getText();
                khoanthu = tfkhoanthu.getText();
                if(ngay.isEmpty()) throw new trongngayException();
                if (!ngay.matches("^\\d{2}[/]\\d{2}[/]\\d{4}$")) throw new NgayException();
                if(sotien.isEmpty()) throw new trongsotienException();
                if(!sotien.matches("\\d+")) throw new numberException();
                if(ghichu.isEmpty()) throw new trongghichuException();
                if(khoanthu.isEmpty()) throw new trongkhoanchiException();
                int tien = Integer.parseInt(sotien);
                Bangthu bc = new Bangthu(ngay , tien, ghichu, khoanthu);
                tm.addRow(bc.toObject());
                lbangthu.add(bc);
                trangthai(true);
                them = false;
            }
            catch(trongngayException e){
                JOptionPane.showMessageDialog(this,"Khong de trong ngay!");
            }
            catch (NgayException e) {
                JOptionPane.showMessageDialog(this,"Nhap dung dinh dang dd/mm/yy");
            }
            catch (trongsotienException e) {
                JOptionPane.showMessageDialog(this,"Khong de trong so tien!");
            } 
            catch (numberException e) {
                JOptionPane.showMessageDialog(this,"Nhap so nguyen duong!");
            }
            catch(trongghichuException e){
                JOptionPane.showMessageDialog(this,"Khong de trong ghi chu!");
            }
            catch (trongkhoanchiException e) {
                JOptionPane.showMessageDialog(this,"Khong de trong khoan chi!");
            }
        }
        if(sua){
            int row = tbbangthu.getSelectedRow();
            String ngay, sotien, ghichu, khoanthu;
            try{
                ngay = tfngay.getText();
                sotien = tfsotien.getText();
                ghichu = tfghichu.getText();
                khoanthu = tfkhoanthu.getText();
                if(ngay.isEmpty()) throw new trongngayException();
                if(sotien.isEmpty()) throw new trongsotienException();
                if(ghichu.isEmpty()) throw new trongghichuException();
                if(khoanthu.isEmpty()) throw new trongkhoanchiException();
                int tien = Integer.parseInt(sotien);
                Bangthu bc = new Bangthu(ngay , tien, ghichu, khoanthu);
                tm.setValueAt(ngay, row, 0);
                tm.setValueAt(sotien, row, 1);
                tm.setValueAt(ghichu, row, 2);
                tm.setValueAt(khoanthu, row, 3);
                lbangthu.set(row, bc);
                trangthai(true);
                sua = false;
            }
            catch(trongngayException e){
                JOptionPane.showMessageDialog(this,"Khong de trong ngay!");
            }
            catch (trongsotienException e) {
                JOptionPane.showMessageDialog(this,"Khong de trong so tien!");
            } 
            catch(trongghichuException e){
                JOptionPane.showMessageDialog(this,"Khong de trong ghi chu!");
            }
            catch (trongkhoanchiException e) {
                JOptionPane.showMessageDialog(this,"Khong de trong khoan chi!");
            }
        }
        IOFile.viet(fbangthu, lbangthu);
    }//GEN-LAST:event_bcapnhatActionPerformed

    private void bxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxoaActionPerformed
        int row = tbbangthu.getSelectedRow();
        if (row < 0 || row > tm.getRowCount()-1) {
            JOptionPane.showMessageDialog(this, "Chon de xoa");
        } 
        else {
            tm.removeRow(row);
            lbangthu.remove(row);
        }
    }//GEN-LAST:event_bxoaActionPerformed

    private void bthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthemActionPerformed

        trangthai(false);
        them = true;
        if(lbangthu == null || lbangthu.size() < 1)
            lbangthu = new ArrayList<>();
        tfngay.requestFocus();
    }//GEN-LAST:event_bthemActionPerformed

    private void bboquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bboquaActionPerformed
        if (them) {
            them = false;
        }
        if (sua) 
            sua = false;
        
        trangthai(true);
    }//GEN-LAST:event_bboquaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bboqua;
    private javax.swing.JButton bcapnhat;
    private javax.swing.JButton bsua;
    private javax.swing.JButton bthem;
    private javax.swing.JButton bxoa;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbbangthu;
    private javax.swing.JTextField tfghichu;
    private javax.swing.JTextField tfkhoanthu;
    private javax.swing.JTextField tfngay;
    private javax.swing.JTextField tfsotien;
    // End of variables declaration//GEN-END:variables
}
