/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.IOFile;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Bangchi;
import model.Bangthu;

/**
 *
 * @author trung
 */
public final class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    private List<Bangthu> lbangthu;
    private String fbangthu;
    
    
    private List<Bangchi> lbangchi;
    private String fbangchi;
    private int tongchi = 0, tongthu = 0;
    private void loadData1() {
        File f = new File(fbangchi);
        if (f.exists()) {
            lbangchi = IOFile.doc(fbangchi);
        } 
        else {
            lbangchi = new ArrayList<>();
        }
    }        
    public void tongchi(){
        fbangchi = "src/controller/Bangchi.DAT";
        if(lbangchi == null || lbangchi.size() < 1)
            lbangchi = new ArrayList<>();
        loadData1();
        tongchi = 0;
        for(Bangchi i: lbangchi)
            tongchi += i.getSotien();
        jtongchi.setText(Integer.toString(tongchi));
    }
    private void loadData() {
        File f = new File(fbangthu);
        if (f.exists()) {
            lbangthu = IOFile.doc(fbangthu);
        } 
        else {
            lbangthu = new ArrayList<>();
        }
    }        
    public void tongthu(){
        fbangthu = "src/controller/Bangthu.DAT";
        if(lbangthu == null || lbangthu.size() < 1)
            lbangthu = new ArrayList<>();
        loadData();
        tongthu = 0;
        for(Bangthu i: lbangthu)
            tongthu += i.getSotien();
        jtongthu.setText(Integer.toString(tongthu));
    }
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
        tongthu();
        tongchi();
        ldu.setText(Integer.toString(tongthu - tongchi));
        Formbangthu fFormbangthu;
        fFormbangthu = new Formbangthu();
        tab.addTab("Bang thu", fFormbangthu);
        Formbangchi fFormbangchi;
        fFormbangchi = new Formbangchi();
        tab.add("Bang chi", fFormbangchi);
        Thongke fthongke;
        fthongke = new Thongke();
        tab.add("Thong ke", fthongke);
        jcapnhat.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        tab = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtongthu = new javax.swing.JLabel();
        jtongchi = new javax.swing.JLabel();
        jcapnhat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ldu = new javax.swing.JLabel();
        anhnen = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        setForeground(new java.awt.Color(51, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab.setForeground(new java.awt.Color(0, 255, 102));
        tab.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        getContentPane().add(tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 660, 470));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Tổng số tiền thu :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, 170, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Tổng số tiền chi :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 160, 34));

        jtongthu.setBackground(new java.awt.Color(153, 255, 0));
        jtongthu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtongthu.setForeground(new java.awt.Color(51, 0, 255));
        jtongthu.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jtongthuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(jtongthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, 180, 40));

        jtongchi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtongchi.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(jtongchi, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 190, 40));

        jcapnhat.setBackground(new java.awt.Color(204, 204, 255));
        jcapnhat.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jcapnhat.setForeground(new java.awt.Color(0, 0, 255));
        jcapnhat.setText("Cập nhật");
        jcapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcapnhatActionPerformed(evt);
            }
        });
        getContentPane().add(jcapnhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 120, 31));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Số dư tài chính :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 452, 150, 30));

        ldu.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        ldu.setForeground(new java.awt.Color(204, 0, 255));
        ldu.setText(" ");
        getContentPane().add(ldu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 170, 40));

        anhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/controller/Anhnen.png"))); // NOI18N
        getContentPane().add(anhnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtongthuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jtongthuAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jtongthuAncestorAdded

    private void jcapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcapnhatActionPerformed
        // TODO add your handling code here:
        tongthu();
        tongchi();
        ldu.setText(Integer.toString(tongthu - tongchi));
    }//GEN-LAST:event_jcapnhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhnen;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jcapnhat;
    private javax.swing.JLabel jtongchi;
    private javax.swing.JLabel jtongthu;
    private javax.swing.JLabel ldu;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
