/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.IOFile;
import controller.NgayException;
import controller.trongngayException;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bangchi;
import model.Bangthu;

/**
 *
 * @author trung
 */
public class Thongke extends javax.swing.JPanel {

    /**
     * Creates new form Thongke
     */
    private boolean trangthaibc = false, trangthaibt = false , trangthaingay = false;
    private List<Bangthu> lbangthu ,lbangt = new ArrayList<>();
    private String fbangthu;
    private List<Bangchi> lbangchi , lbangc = new ArrayList<>();
    private String fbangchi;
    private int tongchi = 0, tongthu = 0;
    private DefaultTableModel tm;
    private void loadData1() {
        fbangchi = "src/controller/Bangchi.DAT";
        File f = new File(fbangchi);
        if (f.exists()) {
            lbangchi = IOFile.doc(fbangchi);
        } 
        else {
            lbangchi = new ArrayList<>();
        }
    }        
    private void loadData() {
        fbangthu = "src/controller/Bangthu.DAT";
        File f = new File(fbangthu);
        if (f.exists()) {
            lbangthu = IOFile.doc(fbangthu);
        } 
        else {
            lbangthu = new ArrayList<>();
        }
    }
    public Thongke() {
        initComponents();
        jngay.setSelected(true);
        jkhoanchi.setSelected(true);
        jcbthang.setEnabled(false);
        tfnam.setEnabled(false);
        String[] cols = {"Ngay", "So tien", "Ghi chu", "Khoan chi"};
        tm = new DefaultTableModel(cols, 0);
        tbbang.setModel(tm);
        jlkhoan.setText("Tong so tien chi: ");
        Date date = new Date();
        ngay_thang.getDateEditor().setDate(date);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbbang = new javax.swing.JTable();
        jkhoanchi = new javax.swing.JRadioButton();
        jtracuu = new javax.swing.JButton();
        jkhoanthu = new javax.swing.JRadioButton();
        jngay = new javax.swing.JRadioButton();
        jthang = new javax.swing.JRadioButton();
        jnam = new javax.swing.JRadioButton();
        ngay_thang = new com.toedter.calendar.JDateChooser();
        tfnam = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbthang = new javax.swing.JComboBox<>();
        jlkhoan = new javax.swing.JLabel();
        jltien = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 102));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setForeground(new java.awt.Color(255, 204, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbbang.setBackground(new java.awt.Color(153, 255, 153));
        tbbang.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tbbang.setForeground(new java.awt.Color(102, 102, 0));
        tbbang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbbang);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 630, 270));

        buttonGroup1.add(jkhoanchi);
        jkhoanchi.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jkhoanchi.setForeground(new java.awt.Color(0, 0, 255));
        jkhoanchi.setText("Khoan chi");
        jkhoanchi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkhoanchiActionPerformed(evt);
            }
        });
        add(jkhoanchi, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 28, -1, -1));

        jtracuu.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jtracuu.setForeground(new java.awt.Color(255, 0, 0));
        jtracuu.setText("Tra cứu");
        jtracuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtracuuActionPerformed(evt);
            }
        });
        add(jtracuu, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, 30));

        buttonGroup1.add(jkhoanthu);
        jkhoanthu.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jkhoanthu.setForeground(new java.awt.Color(0, 0, 255));
        jkhoanthu.setText("Khoan thu");
        jkhoanthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkhoanthuActionPerformed(evt);
            }
        });
        add(jkhoanthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 83, -1, -1));

        buttonGroup2.add(jngay);
        jngay.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jngay.setForeground(new java.awt.Color(0, 0, 255));
        jngay.setText("Ngày  - tháng - năm");
        jngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jngayActionPerformed(evt);
            }
        });
        add(jngay, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        buttonGroup2.add(jthang);
        jthang.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jthang.setForeground(new java.awt.Color(0, 0, 255));
        jthang.setText("Tháng - năm");
        jthang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jthangActionPerformed(evt);
            }
        });
        add(jthang, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        buttonGroup2.add(jnam);
        jnam.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jnam.setForeground(new java.awt.Color(0, 0, 255));
        jnam.setText("Năm");
        jnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnamActionPerformed(evt);
            }
        });
        add(jnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        ngay_thang.setBackground(new java.awt.Color(0, 255, 204));
        ngay_thang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ngay_thang.setForeground(new java.awt.Color(0, 0, 255));
        ngay_thang.setDateFormatString("dd-MM-yyyy");
        add(ngay_thang, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        tfnam.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfnam.setForeground(new java.awt.Color(0, 0, 255));
        add(tfnam, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 74, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Tháng");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Năm");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, -1));

        jcbthang.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jcbthang.setForeground(new java.awt.Color(0, 0, 255));
        jcbthang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        add(jcbthang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 80, 30));

        jlkhoan.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlkhoan.setForeground(new java.awt.Color(255, 0, 0));
        add(jlkhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 190, 40));

        jltien.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jltien.setForeground(new java.awt.Color(0, 204, 51));
        add(jltien, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 125, 270, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jkhoanchiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkhoanchiActionPerformed
        // TODO add your handling code here:
    String[] cols = {"Ngay", "So tien", "Ghi chu", "Khoan chi"};
        tm = new DefaultTableModel(cols, 0);
        tbbang.setModel(tm);
        jlkhoan.setText("Tong so tien chi: ");
        jltien.setText("");
    }//GEN-LAST:event_jkhoanchiActionPerformed

    private void jtracuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtracuuActionPerformed
        // TODO add your handling code here:
        loadData();
        loadData1();
        int tong = 0;
        String ngay = "";
        tbbang.removeAll();
        if(jngay.isSelected()){
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            ngay = sdf.format(ngay_thang.getDate());
            if(jkhoanchi.isSelected()){
                lbangc.clear();
                for(Bangchi i: lbangchi){
                    if(i.getNgay() == null ? ngay == null : i.getNgay().equals(ngay)){
                        lbangc.add(i);
                        tong += i.getSotien();
                    }
                }
                tm.setRowCount(0);
                for(Bangchi i: lbangc){
                    tm.addRow(i.toObject());
                }
                jltien.setText(Integer.toString(tong));
                if(lbangc.size() < 1)
                            JOptionPane.showMessageDialog(this,"Khong co khoan chi nao!");
            }
            else{
                lbangt.clear();
                for(Bangthu i: lbangthu){
                    if(i.getNgay() == null ? ngay == null : i.getNgay().equals(ngay)){
                        lbangt.add(i);
                        tong += i.getSotien();
                    }
                }
                tm.setRowCount(0);
                for(Bangthu i: lbangt){
                    tm.addRow(i.toObject());
                }
                jltien.setText(Integer.toString(tong));
                if(lbangt.size() < 1)
                            JOptionPane.showMessageDialog(this,"Khong co khoan thu nao!");
            }
        }
        else{
            if(jthang.isSelected()){
                try{
                    if(tfnam.getText().isEmpty()) throw new trongngayException();
                    if (!tfnam.getText().matches("^\\d{4}$")) throw new NgayException();
                    ngay += jcbthang.getSelectedItem().toString()+ "-" + tfnam.getText();
                    if(jkhoanchi.isSelected()){
                        lbangc.clear();
                        for(Bangchi i: lbangchi){
                            String s = i.getNgay();
                            boolean ok = true;
                            for(int j = 0 ; j < ngay.length(); j++){
                                if(ngay.charAt(j) != s.charAt(j + 3)){
                                    ok = false;
                                    break;
                                }
                            }
                            if(ok){
                                lbangc.add(i);
                                tong += i.getSotien();
                            }
                        }
                        tm.setRowCount(0);
                        for(Bangchi i: lbangc){
                            tm.addRow(i.toObject());
                        }
                        jltien.setText(Integer.toString(tong));
                        if(lbangc.size() < 1)
                            JOptionPane.showMessageDialog(this,"Khong co khoan chi nao!");
                    }
                    else{
                        lbangt.clear();
                        for(Bangthu i: lbangthu){
                            String s = i.getNgay();
                            boolean ok = true;
                            for(int j = 0 ; j < ngay.length(); j++){
                                if(ngay.charAt(j) != s.charAt(j + 3)){
                                    ok = false;
                                    break;
                                }
                            }
                            if(ok){
                                lbangt.add(i);
                                tong += i.getSotien();
                            }
                        }
                        tm.setRowCount(0);
                        for(Bangthu i: lbangt){
                            tm.addRow(i.toObject());
                        }
                        jltien.setText(Integer.toString(tong));
                        if(lbangt.size() < 1)
                            JOptionPane.showMessageDialog(this,"Khong co khoan thu nao!");
                    }
                }
                catch (trongngayException ex) {
                    JOptionPane.showMessageDialog(this,"Khong de trong ngay!");
                }
                catch (NgayException ex) {
                    JOptionPane.showMessageDialog(this,"Nhap dung dinh dang yyyy!");
                }
                
            }
            else{
                if(jnam.isSelected()){
                    try{
                        if(tfnam.getText().isEmpty()) throw new trongngayException();
                        if (!tfnam.getText().matches("^\\d{4}$")) throw new NgayException();
                        ngay += tfnam.getText();
                        if(jkhoanchi.isSelected()){
                            lbangc.clear();
                            for(Bangchi i: lbangchi){
                                String s = i.getNgay();
                                boolean ok = true;
                                for(int j = 0 ; j < ngay.length(); j++){
                                    if(ngay.charAt(j) != s.charAt(j + 6)){
                                        ok = false;
                                        break;
                                    }
                                }
                                if(ok){
                                    lbangc.add(i);
                                    tong += i.getSotien();
                                }
                            }
                            tm.setRowCount(0);
                            for(Bangchi i: lbangc){
                                tm.addRow(i.toObject());
                            }
                            jltien.setText(Integer.toString(tong));
                            if(lbangc.size() < 1)
                            JOptionPane.showMessageDialog(this,"Khong co khoan chi nao!");
                        }
                        else{
                            lbangt.clear();
                            for(Bangthu i: lbangthu){
                                String s = i.getNgay();
                                boolean ok = true;
                                for(int j = 0 ; j < ngay.length(); j++){
                                    if(ngay.charAt(j) != s.charAt(j + 6)){
                                        ok = false;
                                        break;
                                    }
                                }
                                if(ok){
                                    lbangt.add(i);
                                    tong += i.getSotien();
                                }
                            }
                            tm.setRowCount(0);
                            for(Bangthu i: lbangt){
                                tm.addRow(i.toObject());
                            }
                            jltien.setText(Integer.toString(tong));
                            if(lbangt.size() < 1)
                            JOptionPane.showMessageDialog(this,"Khong co khoan thu nao!");
                        }
                    }
                    catch (trongngayException ex) {
                        JOptionPane.showMessageDialog(this,"Khong de trong ngay!");
                    }
                    catch (NgayException ex) {
                        JOptionPane.showMessageDialog(this,"Nhap dung dinh dang yyyy!");
                    }
                }
                
            }
        }
//        ngay_thang.setEnabled(true);
//        jcbthang.setEnabled(true);
//        tfnam.setEnabled(true);
    }//GEN-LAST:event_jtracuuActionPerformed

    private void jngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jngayActionPerformed
        jcbthang.setEnabled(false);
        tfnam.setEnabled(false);
        ngay_thang.setEnabled(true);
    }//GEN-LAST:event_jngayActionPerformed

    private void jkhoanthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkhoanthuActionPerformed
        String[] cols = {"Ngay", "So tien", "Ghi chu", "Khoan thu"};
        tm = new DefaultTableModel(cols, 0);
        tbbang.setModel(tm);
        jlkhoan.setText("Tong so tien Thu: ");
        jltien.setText("");
    }//GEN-LAST:event_jkhoanthuActionPerformed

    private void jthangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jthangActionPerformed
        // TODO add your handling code here:
        jcbthang.setEnabled(true);
        tfnam.setEnabled(true);
        ngay_thang.setEnabled(false);
    }//GEN-LAST:event_jthangActionPerformed

    private void jnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnamActionPerformed
        // TODO add your handling code here:
        jcbthang.setEnabled(false);
        tfnam.setEnabled(true);
        ngay_thang.setEnabled(false);
    }//GEN-LAST:event_jnamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbthang;
    private javax.swing.JRadioButton jkhoanchi;
    private javax.swing.JRadioButton jkhoanthu;
    private javax.swing.JLabel jlkhoan;
    private javax.swing.JLabel jltien;
    private javax.swing.JRadioButton jnam;
    private javax.swing.JRadioButton jngay;
    private javax.swing.JRadioButton jthang;
    private javax.swing.JButton jtracuu;
    private com.toedter.calendar.JDateChooser ngay_thang;
    private javax.swing.JTable tbbang;
    private javax.swing.JTextField tfnam;
    // End of variables declaration//GEN-END:variables
}
